build:
    environment:
        php:
            version: 8.4
            pecl_extensions:
                - curl
        node: false
        python: false
        ruby: false

    nodes:
        analysis:
            cache:
                disabled: false
                directories:
                    - ~/.composer/cache
            project_setup:
                override:
                    - composer self-update --2
                    - composer install --no-interaction --prefer-dist
            tests:
                override:
                    - php-scrutinizer-run
                    - phpcs-run

checks:
    php:
        code_rating: true
        duplication: true
        coupling: true

tools:
    external_code_coverage:
        runs: 2
        timeout: 600

build_failure_conditions:
    - 'elements.rating(<= C).new.exists'
    - 'issues.severity(>= MAJOR).new.exists'
    - 'project.metric_change("scrutinizer.test_coverage", < -0.5)'
    - 'patches.label("Unused Use Statements").new.exists'
